// Contract interfaces, and nothing else.
//
// This module imports nothing at all, the same discipline lib/config.ts holds
// to. That is what makes it safe for a client component to reach: an ABI is a
// data literal, so pulling this in costs the browser bundle a few hundred bytes
// of JSON and drags no RPC client, no fixtures and no server code behind it.
//
// lib/dreamdex.ts re-exports the four read ABIs from here, so every existing
// importer keeps working unchanged and there is still exactly one definition of
// each.
//
// The PerennisVault entries are generated by hand from
// contracts/src/PerennisVault.sol in this repo, so they are exact. The
// BinaryMarketsModule entries are written from the market structure documented
// at docs.dreamdex.io. Verify those selectors against the contracts and
// addresses page before the demo recording.

/**
 * Exact, taken from contracts/src/PerennisVault.sol in this repo. Signature is
 * event RollSettled(uint256 indexed index, bytes32 indexed marketId, bool won,
 * uint256 payout, uint256 balanceAfter). Renaming it breaks the ledger read and
 * DEMO.md step 5 with it.
 */
export const rollSettledEvent = {
  type: "event",
  name: "RollSettled",
  anonymous: false,
  inputs: [
    { name: "index", type: "uint256", indexed: true },
    { name: "marketId", type: "bytes32", indexed: true },
    { name: "won", type: "bool", indexed: false },
    { name: "payout", type: "uint256", indexed: false },
    { name: "balanceAfter", type: "uint256", indexed: false },
  ],
} as const;

/** Exact, taken from contracts/src/PerennisVault.sol in this repo. */
export const perennisVaultAbi = [
  {
    type: "function",
    name: "snapshot",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "balance", type: "uint256" },
      { name: "status", type: "uint8" },
      { name: "stopReason", type: "uint8" },
      { name: "windowsFilled", type: "uint32" },
      { name: "consecutiveLosses", type: "uint32" },
      { name: "openMarketId", type: "bytes32" },
      { name: "queueLength", type: "uint256" },
      { name: "subscriptionId", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "plan",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "direction", type: "uint8" },
      { name: "stakePerWindow", type: "uint256" },
      { name: "windows", type: "uint32" },
      { name: "maxConsecutiveLosses", type: "uint32" },
      { name: "floorBalance", type: "uint256" },
      { name: "takeProfit", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "rollCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    // `address public immutable owner` on the contract. The ledger compares the
    // transaction sender against this to decide the validator call badge.
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    // The Roll struct the contract stores next to every RollSettled event. It
    // carries the stake, the direction and the settlement timestamp, none of
    // which are in the event payload.
    type: "function",
    name: "rollAt",
    stateMutability: "view",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "marketId", type: "bytes32" },
          { name: "direction", type: "uint8" },
          { name: "stake", type: "uint256" },
          { name: "payout", type: "uint256" },
          { name: "balanceAfter", type: "uint256" },
          { name: "settledAt", type: "uint64" },
          { name: "won", type: "bool" },
        ],
      },
    ],
  },
  rollSettledEvent,
] as const;

/**
 * The five owner and permissionless writes, kept in their own array so the read
 * ABI above stays a literal copy of what Phase 2 shipped. Every entry is exact,
 * including `startPlan` being `payable`: the reactivity subscription is funded
 * out of msg.value, because the owner is billed for every handler run.
 *
 * The Plan tuple order is the struct order in the contract and the encoder
 * depends on it: direction, stakePerWindow, windows, maxConsecutiveLosses,
 * floorBalance, takeProfit.
 */
export const perennisVaultWriteAbi = [
  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "startPlan",
    stateMutability: "payable",
    inputs: [
      {
        name: "p",
        type: "tuple",
        components: [
          { name: "direction", type: "uint8" },
          { name: "stakePerWindow", type: "uint256" },
          { name: "windows", type: "uint32" },
          { name: "maxConsecutiveLosses", type: "uint32" },
          { name: "floorBalance", type: "uint256" },
          { name: "takeProfit", type: "uint256" },
        ],
      },
      { name: "windowIds", type: "bytes32[]" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "armNext",
    stateMutability: "nonpayable",
    inputs: [{ name: "windowIds", type: "bytes32[]" }],
    outputs: [],
  },
  {
    type: "function",
    name: "halt",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
] as const;

/** DreamDEX binary market reads. Verify selectors before recording the demo. */
export const binaryMarketsAbi = [
  {
    type: "function",
    name: "getMarket",
    stateMutability: "view",
    inputs: [{ name: "marketId", type: "bytes32" }],
    outputs: [
      { name: "state", type: "uint8" },
      { name: "lockTime", type: "uint64" },
      { name: "upTokenId", type: "uint256" },
      { name: "downTokenId", type: "uint256" },
    ],
  },
] as const;

/**
 * The ERC20 surface this app touches. `decimals` is read on every path that
 * scales a number, never assumed. `allowance` and `approve` exist because the
 * vault pulls collateral with transferFrom, so a deposit is two transactions
 * whenever the standing allowance is short.
 */
export const erc20Abi = [
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
] as const;
