// Somnia + DreamDEX integration layer.
//
// Every function here has two paths in one body: the real chain call when the
// matching address is configured in lib/config.ts, and the fixtures in
// lib/data/seed.ts when it is not. That means `npm run dev` with an empty
// .env.local gives a full working console, and pointing
// NEXT_PUBLIC_CONTRACT_ADDRESS at a deployed PerennisVault switches the same
// screen onto Shannon without touching a component.
//
// Three rules this module holds to:
//
//   1. No process.env read lives here. Every address, endpoint and constant
//      comes from lib/config.ts.
//   2. Every outbound call goes through withTimeoutAndRetry(). There is exactly
//      one retry loop on the core path and it lives in lib/rpc.ts, which this
//      file and lib/markets.ts both import and this file re-exports.
//   3. Nothing throws out of this module. A failure returns
//      { source: "seed", data: <fixtures>, note } built from a CoreFailure, so
//      the console shows the seed badge and a reason instead of an error page.
//
// The ABIs moved to lib/abi.ts in Phase 3, so the write path can encode against
// the same definitions without importing this module (which would drag viem and
// the RPC layer into the browser bundle). They are re-exported below, so every
// importer that used to take them from here keeps working unchanged. There is
// still exactly one definition of each.
//
// The PerennisVault ABI is exact: it is generated by hand from
// contracts/src/PerennisVault.sol in this repo.
//
// The BinaryMarketsModule ABI is written from the market structure documented at
// docs.dreamdex.io/developers/event-contracts/market-structure. Verify the exact
// selectors against the contracts-and-addresses page before the demo recording:
// if a signature is wrong the call reverts, this module catches it and falls back
// to seed data, and the console shows the "seed data" badge instead of crashing.

import {
  binaryMarketsAbi,
  erc20Abi,
  perennisVaultAbi,
  rollSettledEvent,
} from "@/lib/abi";
import {
  COLLATERAL_TOKEN,
  LEDGER_CHUNK_BLOCKS,
  LEDGER_LOOKBACK_BLOCKS,
  LEDGER_MAX_CHUNKS,
  LEDGER_SCAN_BUDGET_MS,
  MAX_LEDGER_ROWS,
  VAULT_ADDRESS,
} from "./config";
import { classify, coreFailure, failureNote, isFailureNote } from "./errors";
import { logCore, logCoreWarn } from "./log";
import { discoverEventWindows, toBytes32 } from "./markets";
import {
  publicClient,
  recentValue,
  remember,
  somniaShannon,
  withTimeoutAndRetry,
} from "./rpc";
import { eventWindows, vaults } from "./data/seed";
import type {
  ApiResponse,
  Asset,
  Direction,
  EventWindow,
  Plan,
  RollEntry,
  Vault,
} from "./types";

// The Shannon client and the one retry loop moved to lib/rpc.ts in Phase 4, so
// lib/markets.ts can use them without importing this module (which would make
// the two circular). They are re-exported here, along with toBytes32, so every
// importer written before that keeps resolving them from this file.
export { somniaShannon, toBytes32, withTimeoutAndRetry };

export function explorerTxUrl(txHash: string) {
  return `${somniaShannon.blockExplorers.default.url}/tx/${txHash}`;
}

export function explorerAddressUrl(address: string) {
  return `${somniaShannon.blockExplorers.default.url}/address/${address}`;
}

// --- ABIs ----------------------------------------------------------------

// Defined in lib/abi.ts, which imports nothing, and re-exported here so the
// importers written before Phase 3 keep resolving them from this module.
export { binaryMarketsAbi, erc20Abi, perennisVaultAbi, rollSettledEvent };

// The lifecycle code table moved to lib/markets.ts with the per id read that
// uses it, so there is one place that turns a market state code into a label.

const ZERO_BYTES32 =
  "0x0000000000000000000000000000000000000000000000000000000000000000";

// --- Reads ---------------------------------------------------------------

/**
 * The window queue the plan builder writes into the vault.
 *
 * A thin wrapper over discoverEventWindows() in lib/markets.ts, which owns the
 * three level fallback: the sponsor SDK first, then the per id getMarket read
 * that used to live in this function, then the fixtures. Each level that does
 * not answer attaches a note written by us, so a fixture list never renders
 * under a chain badge without saying why.
 *
 * This function keeps its name and its return shape because both adapters, both
 * API routes and DEMO.md step 2 are written against them.
 */
export async function fetchEventWindows(): Promise<ApiResponse<EventWindow[]>> {
  const { response } = await discoverEventWindows();
  return response;
}

/**
 * The roll ledger, read back from RollSettled logs on the deployed vault.
 *
 * This is the mechanism Phase 2 took off fixtures. Every row carries a real
 * transaction hash and a real block number, so DEMO.md step 5 can open the row
 * on the Shannon explorer.
 *
 * Bounded on purpose, at four separate points:
 *   - the lookback is walked in LEDGER_CHUNK_BLOCKS spans, newest first, and no
 *     single eth_getLogs ever asks for a wider range than that
 *   - at most LEDGER_MAX_CHUNKS spans are walked, and the walk stops early both
 *     on LEDGER_SCAN_BUDGET_MS and as soon as it holds MAX_LEDGER_ROWS rows
 *   - at most MAX_LEDGER_ROWS logs are kept, the most recent ones
 *   - the per row follow up reads run only over those kept logs
 * There is no unbounded loop anywhere on this path.
 *
 * The span walk is the fix for the QA finding that put a fixture ledger under a
 * live Shannon badge. This function used to ask for the whole lookback in one
 * call. Public JSON-RPC endpoints cap the block span of an eth_getLogs and
 * answer anything wider with a rejection rather than a short result, so that one
 * call failed every time, deterministically, and the retry re-sent exactly the
 * request that had just been refused. Asking within the cap is the difference
 * between a ledger and a fallback notice.
 *
 * `trigger` is derived, not assumed: the sender of the transaction that emitted
 * the log is compared against owner() on the vault. A sender that is not the
 * owner means the roll was produced by the validator synthetic call in the
 * settlement block, which is exactly the claim the demo makes on camera.
 */
export async function fetchRollLedger(
  decimalsHint?: number
): Promise<ApiResponse<RollEntry[]>> {
  const seedLedger = vaults[1].ledger;

  if (!VAULT_ADDRESS) {
    return {
      source: "seed",
      data: seedLedger,
      note: failureNote(
        coreFailure(
          "not-configured",
          "No vault address is set, so the roll ledger comes from the fixtures."
        )
      ),
    };
  }

  try {
    const client = publicClient();
    const address = VAULT_ADDRESS;

    const latest = await withTimeoutAndRetry(() => client.getBlockNumber());
    const scan = await scanRollLogs(address, latest);

    // Most recent rows only. Everything after this point iterates a list whose
    // length is capped by MAX_LEDGER_ROWS.
    const recent = scan.logs
      .filter((log) => log.transactionHash !== null)
      .slice(-MAX_LEDGER_ROWS);

    logCore("ledger logs read", {
      rows: recent.length,
      spans: scan.spansRead,
      lookback: LEDGER_LOOKBACK_BLOCKS.toString(),
    });

    if (recent.length === 0) {
      return remember(LEDGER_CACHE_KEY, {
        source: "chain",
        data: [],
        // A partial walk cannot claim the lookback is empty, only that the part
        // of it Shannon served held no settlement.
        note: scan.complete
          ? "No RollSettled logs in the lookback window yet. The first row lands when the open window settles."
          : failureNote(
              coreFailure(
                "upstream-error",
                "Shannon served part of the ledger lookback, and no window had settled in the part that came back."
              )
            ),
      } satisfies ApiResponse<RollEntry[]>);
    }

    const decimals = decimalsHint ?? (await fetchCollateralDecimals());
    const scale = 10 ** decimals;

    const ownerAddress = await withTimeoutAndRetry(() =>
      client.readContract({ address, abi: perennisVaultAbi, functionName: "owner" })
    ).catch(() => null);

    const senders = await senderByTxHash(recent.map((log) => log.transactionHash!));

    const details = await Promise.allSettled(
      recent.map((log) =>
        withTimeoutAndRetry(() =>
          client.readContract({
            address,
            abi: perennisVaultAbi,
            functionName: "rollAt",
            args: [log.args.index ?? 0n],
          })
        )
      )
    );

    const data: RollEntry[] = recent.map((log, i): RollEntry => {
      const detail = details[i];
      const roll = detail.status === "fulfilled" ? detail.value : null;

      const marketId = (log.args.marketId ?? ZERO_BYTES32) as string;
      const stake = roll ? Number(roll.stake) / scale : 0;
      const payout = Number(log.args.payout ?? 0n) / scale;
      const direction: Direction =
        roll && Number(roll.direction) === 1 ? "DOWN" : "UP";
      const won = Boolean(log.args.won);

      const sender = senders.get(log.transactionHash!.toLowerCase()) ?? null;
      // No owner read and no sender read means we cannot prove who sent it, so
      // the row is labelled manual rather than claiming a validator call.
      const isOwnerCall =
        ownerAddress !== null &&
        sender !== null &&
        sender === ownerAddress.toLowerCase();

      return {
        index: Number(log.args.index ?? 0n) + 1,
        marketId,
        asset: assetForMarket(marketId),
        direction,
        entryCents: entryCentsFrom(marketId, direction, stake, payout, won),
        stake: round2(stake),
        // The event carries a boolean, not a three way outcome, so a voided
        // market reads as LOST here until the markets module exposes the
        // settlement mode. Recorded in HANDOFF.md as a known gap.
        outcome: won ? "WON" : "LOST",
        payout: round2(payout),
        balanceAfter: round2(Number(log.args.balanceAfter ?? 0n) / scale),
        settledAt: roll
          ? new Date(Number(roll.settledAt) * 1000).toISOString()
          : new Date(0).toISOString(),
        blockNumber: Number(log.blockNumber ?? 0n),
        txHash: log.transactionHash!,
        trigger: isOwnerCall ? "manual" : "reactivity",
      };
    });

    return remember(LEDGER_CACHE_KEY, {
      source: "chain",
      data,
    } satisfies ApiResponse<RollEntry[]>);
  } catch (error) {
    return recentOr(
      LEDGER_CACHE_KEY,
      seedLedger,
      "ledger logs read",
      "the roll ledger",
      error
    );
  }
}

const LEDGER_CACHE_KEY = "roll-ledger";
const VAULTS_CACHE_KEY = "vaults";
const DECIMALS_CACHE_KEY = "collateral-decimals";

/**
 * Walk the lookback backwards in LEDGER_CHUNK_BLOCKS spans and collect the
 * RollSettled logs, newest span first.
 *
 * Why backwards: the ledger only ever renders the newest MAX_LEDGER_ROWS rows,
 * so the newest span is the one most likely to answer the question, and a vault
 * settling regularly is done after a single call. The full walk is the empty
 * vault case, and LEDGER_SCAN_BUDGET_MS is what keeps that case off the page's
 * render budget.
 *
 * One refused span does not sink the ledger. The rows already collected from
 * newer spans are worth more than the ones the endpoint would not serve, so the
 * walk records that it is incomplete and returns what it has. It only throws when
 * nothing answered at all, which is a genuine upstream failure and the one case
 * that should reach the fixtures.
 */
async function scanRollLogs(
  address: `0x${string}`,
  latest: bigint
): Promise<{ logs: RollLog[]; complete: boolean; spansRead: number }> {
  const deadline = Date.now() + LEDGER_SCAN_BUDGET_MS;
  const floor =
    latest > LEDGER_LOOKBACK_BLOCKS ? latest - LEDGER_LOOKBACK_BLOCKS : 0n;

  let collected: RollLog[] = [];
  let toBlock = latest;
  let spans = 0;
  let spansRead = 0;
  let complete = true;
  // Seeded, the same way withTimeoutAndRetry() seeds its own, so the throw below
  // always has something to throw and never has to widen an unknown.
  let lastError: unknown = new Error("ledger scan read no span");

  while (spans < LEDGER_MAX_CHUNKS && toBlock >= floor) {
    // Checked before the span is issued, not after it returns, so the budget
    // bounds how long the walk may start work for rather than how long it may
    // have already spent. Blocks are still unread at this point by definition of
    // the loop guard, so the walk is incomplete and says so.
    if (Date.now() > deadline) {
      complete = false;
      break;
    }

    // Width is taken from what is left rather than subtracted blindly, so
    // fromBlock can never run below floor and the bigint can never go negative.
    const remaining = toBlock - floor + 1n;
    const width =
      remaining < LEDGER_CHUNK_BLOCKS ? remaining : LEDGER_CHUNK_BLOCKS;
    const fromBlock = toBlock - width + 1n;

    try {
      const batch = await getRollLogs(address, fromBlock, toBlock);
      // Older spans go in front, so the collected list stays in block order and
      // the slice(-MAX_LEDGER_ROWS) below still takes the newest rows. concat
      // rather than unshift(...batch): a busy span would spread thousands of
      // arguments onto the stack, and this has no argument count to blow.
      collected = batch.concat(collected);
      spansRead += 1;
    } catch (error) {
      lastError = error;
      complete = false;
      logCoreWarn("ledger span refused", {
        from: fromBlock.toString(),
        to: toBlock.toString(),
        code: classify(error),
      });
    }

    spans += 1;
    // A full page of rows is every row the ledger will render, and they are the
    // newest ones because the walk started at the head. Older spans cannot
    // change what is shown, so there is no reason to pay for them.
    if (collected.length >= MAX_LEDGER_ROWS) break;

    toBlock = fromBlock - 1n;
  }

  // Nothing answered. That is upstream being down, not a quiet ledger.
  if (spansRead === 0) throw lastError;

  return { logs: collected, complete, spansRead };
}

/** One span, through the single retry loop. Split out so scanRollLogs reads as a walk. */
function getRollLogs(
  address: `0x${string}`,
  fromBlock: bigint,
  toBlock: bigint
) {
  const client = publicClient();
  return withTimeoutAndRetry(() =>
    client.getLogs({ address, event: rollSettledEvent, fromBlock, toBlock })
  );
}

/** A decoded RollSettled log, taken from the call rather than restated by hand. */
type RollLog = Awaited<ReturnType<typeof getRollLogs>>[number];

/**
 * One transaction read per unique hash, so twelve ledger rows produced by three
 * transactions cost three calls and not twelve. Returns lowercased senders keyed
 * by lowercased hash.
 */
async function senderByTxHash(
  hashes: readonly `0x${string}`[]
): Promise<Map<string, string>> {
  const client = publicClient();
  const unique = Array.from(new Set(hashes.map((h) => h.toLowerCase())));

  const results = await Promise.allSettled(
    unique.map((hash) =>
      withTimeoutAndRetry(() =>
        client.getTransaction({ hash: hash as `0x${string}` })
      )
    )
  );

  const map = new Map<string, string>();
  results.forEach((result, i) => {
    if (result.status === "fulfilled" && result.value.from) {
      map.set(unique[i], result.value.from.toLowerCase());
    }
  });
  return map;
}

/**
 * Vault state. Chain path reads the deployed PerennisVault; the ABI above is
 * generated from the contract in this repo, so this call is the real thing.
 * The ledger is no longer seeded when the chain path works: fetchRollLedger()
 * supplies it, and the fixture ledger is only the fallback.
 */
export async function fetchVaults(): Promise<ApiResponse<Vault[]>> {
  if (!VAULT_ADDRESS) {
    return {
      source: "seed",
      data: vaults,
      note: failureNote(
        coreFailure(
          "not-configured",
          "No vault address is set, so the console is on seed data."
        )
      ),
    };
  }

  try {
    const client = publicClient();
    const address = VAULT_ADDRESS;

    const [snapshot, planRow] = await Promise.all([
      withTimeoutAndRetry(() =>
        client.readContract({
          address,
          abi: perennisVaultAbi,
          functionName: "snapshot",
        })
      ),
      withTimeoutAndRetry(() =>
        client.readContract({
          address,
          abi: perennisVaultAbi,
          functionName: "plan",
        })
      ),
    ]);

    const decimals = await fetchCollateralDecimals();
    const scale = 10 ** decimals;

    const [
      balance,
      status,
      stopReason,
      windowsFilled,
      consecutiveLosses,
      openMarketId,
      queueLength,
      subscriptionId,
    ] = snapshot;
    const [
      direction,
      stakePerWindow,
      planWindows,
      maxConsecutiveLosses,
      floorBalance,
      takeProfit,
    ] = planRow;

    logCore("vault snapshot read", {
      windowsFilled: Number(windowsFilled),
      queue: Number(queueLength),
    });

    // The ledger comes off RollSettled logs. If that read falls back to seed
    // the note travels with it, so the console never shows a fixture ledger
    // under a chain badge without saying so.
    const ledger = await fetchRollLedger(decimals);

    const live: Vault = {
      ...vaults[1],
      id: "vault-live",
      address,
      label: "Live vault",
      balance: Number(balance) / scale,
      status: (["IDLE", "ACTIVE", "STOPPED", "COMPLETED"] as const)[
        Number(status)
      ],
      stopReason: (
        [
          null,
          "consecutive-losses",
          "floor-balance",
          "take-profit",
          "plan-complete",
          "owner-halt",
        ] as const
      )[Number(stopReason)],
      windowsFilled: Number(windowsFilled),
      consecutiveLosses: Number(consecutiveLosses),
      openMarketId: openMarketId === ZERO_BYTES32 ? null : openMarketId,
      queue: new Array(Number(queueLength)).fill(""),
      plan: {
        asset: "BTC",
        direction: Number(direction) === 0 ? "UP" : "DOWN",
        stakePerWindow: Number(stakePerWindow) / scale,
        windows: Number(planWindows),
        rules: {
          maxConsecutiveLosses: Number(maxConsecutiveLosses),
          floorBalance: Number(floorBalance) / scale,
          takeProfit: Number(takeProfit) / scale,
        },
      } satisfies Plan,
      subscription: {
        ...vaults[1].subscription,
        subscriptionId: Number(subscriptionId),
      },
      ledger: ledger.data,
    };

    return remember(VAULTS_CACHE_KEY, {
      source: "chain",
      data: [vaults[0], live, vaults[2]],
      // A ledger note travels up when it reports a degraded read, whether that
      // was a full fallback to fixtures or a partial walk, so a chain badge never
      // sits over rows this module cannot vouch for without a sentence naming
      // them. "No window has settled yet" is not a degraded read and stays down
      // on the ledger card, which already says exactly that.
      ...(ledger.note && isFailureNote(ledger.note)
        ? { note: ledger.note }
        : {}),
    } satisfies ApiResponse<Vault[]>);
  } catch (error) {
    return recentOr(
      VAULTS_CACHE_KEY,
      vaults,
      "vault snapshot read",
      "the vault state",
      error
    );
  }
}

/**
 * Collateral decimals are read from the token, never assumed. tUSDC on Shannon
 * is 6 decimals but the mainnet USDso deployment does not have to match.
 */
export async function fetchCollateralDecimals(): Promise<number> {
  if (!COLLATERAL_TOKEN) return 6;
  try {
    const token = COLLATERAL_TOKEN;
    const decimals = await withTimeoutAndRetry(() =>
      publicClient().readContract({
        address: token,
        abi: erc20Abi,
        functionName: "decimals",
      })
    );
    logCore("decimals read", { decimals: Number(decimals) });
    return remember(DECIMALS_CACHE_KEY, Number(decimals));
  } catch {
    // The last value read off this token beats the assumed 6, because a token
    // that is not 6 decimals would otherwise misprice the whole console for the
    // length of one refused call.
    const recent = recentValue<number>(DECIMALS_CACHE_KEY);
    logCoreWarn("chain read failed", {
      step: "decimals read",
      code: "upstream-error",
      served: recent === undefined ? "assumed" : "cached",
    });
    return recent ?? 6;
  }
}

// The pre-write safety checks live in lib/vault.ts: they are pure, and keeping
// them out of this module keeps viem off the client bundle.

// --- helpers -------------------------------------------------------------

/**
 * The last good value for this read if there is one, and only otherwise the
 * fixtures.
 *
 * This is the order that matters for the console. A read Shannon refuses once
 * should not throw away numbers that were live twenty seconds ago and replace
 * them with fixtures plus a notice; it should show what it had and stay quiet.
 * The fixture path is what is left when there is nothing recent to serve, which
 * on a cold instance is the first refused read and is honest about it.
 */
function recentOr<T>(
  key: string,
  data: T,
  step: string,
  subject: string,
  error: unknown
): ApiResponse<T> {
  const recent = recentValue<ApiResponse<T>>(key);
  if (recent) {
    const code = classify(error);
    logCoreWarn("chain read failed", { step, code, served: "cached" });

    // The rows really did come off Shannon, so the source stays "chain" and the
    // badge is not made to lie. But they came off it a moment ago rather than
    // just now, and a screen that does not say so is claiming a read it did not
    // get. The note is what makes the difference visible.
    return {
      ...recent,
      note: failureNote(
        coreFailure(
          code,
          `Shannon did not answer ${subject} on this read, so ${subject} below is the last reading it returned.`
        )
      ),
    };
  }
  return seedFallback(data, step, subject, error);
}

/**
 * The one failure shape. Logs a single line carrying the step name and the error
 * code, never the provider message and never the error object, then hands back
 * the fixtures with a sentence written by us.
 *
 * On the wording: this note is rendered on a page a judge is reading, under a
 * console that still works. It says which read did not answer and where the
 * figures below it came from, and it does not reach for the vocabulary of a
 * crash to do it. The machine code is still on the front for GET /api/health;
 * noteHint() in lib/errors.ts takes it off before the console renders it.
 */
function seedFallback<T>(
  data: T,
  step: string,
  subject: string,
  error: unknown
): ApiResponse<T> {
  const code = classify(error);
  logCoreWarn("chain read failed", { step, code, served: "seed" });

  const hint =
    code === "upstream-timeout"
      ? `Shannon did not answer ${subject} in time, so the figures below come from the fixture set.`
      : `Shannon did not return ${subject} on this read, so the figures below come from the fixture set.`;

  return { source: "seed", data, note: failureNote(coreFailure(code, hint)) };
}

// toBytes32() is defined in lib/markets.ts now, next to the per id read that
// needs it, and is re-exported at the top of this file. It still serves the
// fallback path: fixture ids are the shortened form the DreamDEX UI displays and
// have to be right padded, while ids arriving full length from the SDK are
// already 64 hex characters and pass through unchanged.

/** The fixture window a chain market id corresponds to, when there is one. */
function windowFor(marketId: string): EventWindow | undefined {
  const target = marketId.toLowerCase();
  return eventWindows.find((w) => toBytes32(w.marketId).toLowerCase() === target);
}

function assetForMarket(marketId: string): Asset {
  return windowFor(marketId)?.asset ?? "BTC";
}

/**
 * The entry price is not in the RollSettled payload. Two ways to recover it,
 * in order of confidence:
 *   1. a winning roll pays 1 per contract, so stake divided by payout is the
 *      price actually paid
 *   2. otherwise fall back to the book price on the matching window
 * A losing roll on an unknown market leaves 0, which the console renders as 0c
 * rather than inventing a number.
 */
function entryCentsFrom(
  marketId: string,
  direction: Direction,
  stake: number,
  payout: number,
  won: boolean
): number {
  if (won && payout > 0 && stake > 0) {
    return Math.round((stake / payout) * 100);
  }
  const window = windowFor(marketId);
  if (!window) return 0;
  return direction === "UP" ? window.upAskCents : window.downAskCents;
}

function round2(n: number) {
  return Math.round(n * 100) / 100;
}
