// Somnia + DreamDEX integration layer.
//
// Every function here has two paths in one body: the real chain call when the
// matching address is configured in lib/config.ts, and the fixtures in
// lib/data/seed.ts when it is not. That means `npm run dev` with an empty
// .env.local gives a full working console, and pointing
// NEXT_PUBLIC_CONTRACT_ADDRESS at a deployed PerennisVault switches the same
// screen onto Shannon without touching a component.
//
// Three rules this module holds to:
//
//   1. No process.env read lives here. Every address, endpoint and constant
//      comes from lib/config.ts.
//   2. Every outbound call goes through withTimeoutAndRetry(). There is exactly
//      one retry loop on the core path and it lives in lib/rpc.ts, which this
//      file and lib/markets.ts both import and this file re-exports.
//   3. Nothing throws out of this module. A failure returns
//      { source: "seed", data: <fixtures>, note } built from a CoreFailure, so
//      the console shows the seed badge and a reason instead of an error page.
//
// The ABIs moved to lib/abi.ts in Phase 3, so the write path can encode against
// the same definitions without importing this module (which would drag viem and
// the RPC layer into the browser bundle). They are re-exported below, so every
// importer that used to take them from here keeps working unchanged. There is
// still exactly one definition of each.
//
// The PerennisVault ABI is exact: it is generated by hand from
// contracts/src/PerennisVault.sol in this repo.
//
// The BinaryMarketsModule ABI is written from the market structure documented at
// docs.dreamdex.io/developers/event-contracts/market-structure. Verify the exact
// selectors against the contracts-and-addresses page before the demo recording:
// if a signature is wrong the call reverts, this module catches it and falls back
// to seed data, and the console shows the "seed data" badge instead of crashing.

import {
  binaryMarketsAbi,
  erc20Abi,
  perennisVaultAbi,
  rollSettledEvent,
} from "@/lib/abi";
import {
  COLLATERAL_TOKEN,
  LEDGER_LOOKBACK_BLOCKS,
  MAX_LEDGER_ROWS,
  VAULT_ADDRESS,
} from "./config";
import { classify, coreFailure, failureNote } from "./errors";
import { logCore } from "./log";
import { discoverEventWindows, toBytes32 } from "./markets";
import { publicClient, somniaShannon, withTimeoutAndRetry } from "./rpc";
import { eventWindows, vaults } from "./data/seed";
import type {
  ApiResponse,
  Asset,
  Direction,
  EventWindow,
  Plan,
  RollEntry,
  Vault,
} from "./types";

// The Shannon client and the one retry loop moved to lib/rpc.ts in Phase 4, so
// lib/markets.ts can use them without importing this module (which would make
// the two circular). They are re-exported here, along with toBytes32, so every
// importer written before that keeps resolving them from this file.
export { somniaShannon, toBytes32, withTimeoutAndRetry };

export function explorerTxUrl(txHash: string) {
  return `${somniaShannon.blockExplorers.default.url}/tx/${txHash}`;
}

export function explorerAddressUrl(address: string) {
  return `${somniaShannon.blockExplorers.default.url}/address/${address}`;
}

// --- ABIs ----------------------------------------------------------------

// Defined in lib/abi.ts, which imports nothing, and re-exported here so the
// importers written before Phase 3 keep resolving them from this module.
export { binaryMarketsAbi, erc20Abi, perennisVaultAbi, rollSettledEvent };

// The lifecycle code table moved to lib/markets.ts with the per id read that
// uses it, so there is one place that turns a market state code into a label.

const ZERO_BYTES32 =
  "0x0000000000000000000000000000000000000000000000000000000000000000";

// --- Reads ---------------------------------------------------------------

/**
 * The window queue the plan builder writes into the vault.
 *
 * A thin wrapper over discoverEventWindows() in lib/markets.ts, which owns the
 * three level fallback: the sponsor SDK first, then the per id getMarket read
 * that used to live in this function, then the fixtures. Each level that does
 * not answer attaches a note written by us, so a fixture list never renders
 * under a chain badge without saying why.
 *
 * This function keeps its name and its return shape because both adapters, both
 * API routes and DEMO.md step 2 are written against them.
 */
export async function fetchEventWindows(): Promise<ApiResponse<EventWindow[]>> {
  const { response } = await discoverEventWindows();
  return response;
}

/**
 * The roll ledger, read back from RollSettled logs on the deployed vault.
 *
 * This is the mechanism Phase 2 took off fixtures. Every row carries a real
 * transaction hash and a real block number, so DEMO.md step 5 can open the row
 * on the Shannon explorer.
 *
 * Bounded on purpose, at three separate points:
 *   - fromBlock is latest minus LEDGER_LOOKBACK_BLOCKS, never block zero, so a
 *     provider that refuses an unbounded range still answers
 *   - at most MAX_LEDGER_ROWS logs are kept, the most recent ones
 *   - the per row follow up reads run only over those kept logs
 * There is no unbounded loop anywhere on this path.
 *
 * `trigger` is derived, not assumed: the sender of the transaction that emitted
 * the log is compared against owner() on the vault. A sender that is not the
 * owner means the roll was produced by the validator synthetic call in the
 * settlement block, which is exactly the claim the demo makes on camera.
 */
export async function fetchRollLedger(
  decimalsHint?: number
): Promise<ApiResponse<RollEntry[]>> {
  const seedLedger = vaults[1].ledger;

  if (!VAULT_ADDRESS) {
    return {
      source: "seed",
      data: seedLedger,
      note: failureNote(
        coreFailure(
          "not-configured",
          "No vault address is set, so the roll ledger comes from the fixtures."
        )
      ),
    };
  }

  try {
    const client = publicClient();
    const address = VAULT_ADDRESS;

    const latest = await withTimeoutAndRetry(() => client.getBlockNumber());
    const fromBlock =
      latest > LEDGER_LOOKBACK_BLOCKS ? latest - LEDGER_LOOKBACK_BLOCKS : 0n;

    const logs = await withTimeoutAndRetry(() =>
      client.getLogs({
        address,
        event: rollSettledEvent,
        fromBlock,
        toBlock: "latest",
      })
    );

    // Most recent rows only. Everything after this point iterates a list whose
    // length is capped by MAX_LEDGER_ROWS.
    const recent = logs
      .filter((log) => log.transactionHash !== null)
      .slice(-MAX_LEDGER_ROWS);

    logCore("ledger logs read", {
      rows: recent.length,
      lookback: LEDGER_LOOKBACK_BLOCKS.toString(),
    });

    if (recent.length === 0) {
      return {
        source: "chain",
        data: [],
        note: "No RollSettled logs in the lookback window yet. The first row lands when the open window settles.",
      };
    }

    const decimals = decimalsHint ?? (await fetchCollateralDecimals());
    const scale = 10 ** decimals;

    const ownerAddress = await withTimeoutAndRetry(() =>
      client.readContract({ address, abi: perennisVaultAbi, functionName: "owner" })
    ).catch(() => null);

    const senders = await senderByTxHash(recent.map((log) => log.transactionHash!));

    const details = await Promise.allSettled(
      recent.map((log) =>
        withTimeoutAndRetry(() =>
          client.readContract({
            address,
            abi: perennisVaultAbi,
            functionName: "rollAt",
            args: [log.args.index ?? 0n],
          })
        )
      )
    );

    const data: RollEntry[] = recent.map((log, i): RollEntry => {
      const detail = details[i];
      const roll = detail.status === "fulfilled" ? detail.value : null;

      const marketId = (log.args.marketId ?? ZERO_BYTES32) as string;
      const stake = roll ? Number(roll.stake) / scale : 0;
      const payout = Number(log.args.payout ?? 0n) / scale;
      const direction: Direction =
        roll && Number(roll.direction) === 1 ? "DOWN" : "UP";
      const won = Boolean(log.args.won);

      const sender = senders.get(log.transactionHash!.toLowerCase()) ?? null;
      // No owner read and no sender read means we cannot prove who sent it, so
      // the row is labelled manual rather than claiming a validator call.
      const isOwnerCall =
        ownerAddress !== null &&
        sender !== null &&
        sender === ownerAddress.toLowerCase();

      return {
        index: Number(log.args.index ?? 0n) + 1,
        marketId,
        asset: assetForMarket(marketId),
        direction,
        entryCents: entryCentsFrom(marketId, direction, stake, payout, won),
        stake: round2(stake),
        // The event carries a boolean, not a three way outcome, so a voided
        // market reads as LOST here until the markets module exposes the
        // settlement mode. Recorded in HANDOFF.md as a known gap.
        outcome: won ? "WON" : "LOST",
        payout: round2(payout),
        balanceAfter: round2(Number(log.args.balanceAfter ?? 0n) / scale),
        settledAt: roll
          ? new Date(Number(roll.settledAt) * 1000).toISOString()
          : new Date(0).toISOString(),
        blockNumber: Number(log.blockNumber ?? 0n),
        txHash: log.transactionHash!,
        trigger: isOwnerCall ? "manual" : "reactivity",
      };
    });

    return { source: "chain", data };
  } catch (error) {
    return seedFallback(seedLedger, "ledger logs read", error);
  }
}

/**
 * One transaction read per unique hash, so twelve ledger rows produced by three
 * transactions cost three calls and not twelve. Returns lowercased senders keyed
 * by lowercased hash.
 */
async function senderByTxHash(
  hashes: readonly `0x${string}`[]
): Promise<Map<string, string>> {
  const client = publicClient();
  const unique = Array.from(new Set(hashes.map((h) => h.toLowerCase())));

  const results = await Promise.allSettled(
    unique.map((hash) =>
      withTimeoutAndRetry(() =>
        client.getTransaction({ hash: hash as `0x${string}` })
      )
    )
  );

  const map = new Map<string, string>();
  results.forEach((result, i) => {
    if (result.status === "fulfilled" && result.value.from) {
      map.set(unique[i], result.value.from.toLowerCase());
    }
  });
  return map;
}

/**
 * Vault state. Chain path reads the deployed PerennisVault; the ABI above is
 * generated from the contract in this repo, so this call is the real thing.
 * The ledger is no longer seeded when the chain path works: fetchRollLedger()
 * supplies it, and the fixture ledger is only the fallback.
 */
export async function fetchVaults(): Promise<ApiResponse<Vault[]>> {
  if (!VAULT_ADDRESS) {
    return {
      source: "seed",
      data: vaults,
      note: failureNote(
        coreFailure(
          "not-configured",
          "No vault address is set, so the console is on seed data."
        )
      ),
    };
  }

  try {
    const client = publicClient();
    const address = VAULT_ADDRESS;

    const [snapshot, planRow] = await Promise.all([
      withTimeoutAndRetry(() =>
        client.readContract({
          address,
          abi: perennisVaultAbi,
          functionName: "snapshot",
        })
      ),
      withTimeoutAndRetry(() =>
        client.readContract({
          address,
          abi: perennisVaultAbi,
          functionName: "plan",
        })
      ),
    ]);

    const decimals = await fetchCollateralDecimals();
    const scale = 10 ** decimals;

    const [
      balance,
      status,
      stopReason,
      windowsFilled,
      consecutiveLosses,
      openMarketId,
      queueLength,
      subscriptionId,
    ] = snapshot;
    const [
      direction,
      stakePerWindow,
      planWindows,
      maxConsecutiveLosses,
      floorBalance,
      takeProfit,
    ] = planRow;

    logCore("vault snapshot read", {
      windowsFilled: Number(windowsFilled),
      queue: Number(queueLength),
    });

    // The ledger comes off RollSettled logs. If that read falls back to seed
    // the note travels with it, so the console never shows a fixture ledger
    // under a chain badge without saying so.
    const ledger = await fetchRollLedger(decimals);

    const live: Vault = {
      ...vaults[1],
      id: "vault-live",
      address,
      label: "Live vault",
      balance: Number(balance) / scale,
      status: (["IDLE", "ACTIVE", "STOPPED", "COMPLETED"] as const)[
        Number(status)
      ],
      stopReason: (
        [
          null,
          "consecutive-losses",
          "floor-balance",
          "take-profit",
          "plan-complete",
          "owner-halt",
        ] as const
      )[Number(stopReason)],
      windowsFilled: Number(windowsFilled),
      consecutiveLosses: Number(consecutiveLosses),
      openMarketId: openMarketId === ZERO_BYTES32 ? null : openMarketId,
      queue: new Array(Number(queueLength)).fill(""),
      plan: {
        asset: "BTC",
        direction: Number(direction) === 0 ? "UP" : "DOWN",
        stakePerWindow: Number(stakePerWindow) / scale,
        windows: Number(planWindows),
        rules: {
          maxConsecutiveLosses: Number(maxConsecutiveLosses),
          floorBalance: Number(floorBalance) / scale,
          takeProfit: Number(takeProfit) / scale,
        },
      } satisfies Plan,
      subscription: {
        ...vaults[1].subscription,
        subscriptionId: Number(subscriptionId),
      },
      ledger: ledger.data,
    };

    return {
      source: "chain",
      data: [vaults[0], live, vaults[2]],
      ...(ledger.source === "seed" && ledger.note
        ? { note: ledger.note }
        : {}),
    };
  } catch (error) {
    return seedFallback(vaults, "vault snapshot read", error);
  }
}

/**
 * Collateral decimals are read from the token, never assumed. tUSDC on Shannon
 * is 6 decimals but the mainnet USDso deployment does not have to match.
 */
export async function fetchCollateralDecimals(): Promise<number> {
  if (!COLLATERAL_TOKEN) return 6;
  try {
    const token = COLLATERAL_TOKEN;
    const decimals = await withTimeoutAndRetry(() =>
      publicClient().readContract({
        address: token,
        abi: erc20Abi,
        functionName: "decimals",
      })
    );
    logCore("decimals read", { decimals: Number(decimals) });
    return Number(decimals);
  } catch {
    logCore("chain read failed", { step: "decimals read", code: "upstream-error" });
    return 6;
  }
}

// The pre-write safety checks live in lib/vault.ts: they are pure, and keeping
// them out of this module keeps viem off the client bundle.

// --- helpers -------------------------------------------------------------

/**
 * The one failure shape. Logs a single line carrying the step name and the error
 * code, never the provider message and never the error object, then hands back
 * the fixtures with a hint written by us.
 */
function seedFallback<T>(data: T, step: string, error: unknown): ApiResponse<T> {
  const code = classify(error);
  logCore("chain read failed", { step, code });

  const hint =
    code === "upstream-timeout"
      ? "The Shannon RPC did not answer in time, so this screen fell back to seed data."
      : "The Shannon RPC rejected the read, so this screen fell back to seed data.";

  return { source: "seed", data, note: failureNote(coreFailure(code, hint)) };
}

// toBytes32() is defined in lib/markets.ts now, next to the per id read that
// needs it, and is re-exported at the top of this file. It still serves the
// fallback path: fixture ids are the shortened form the DreamDEX UI displays and
// have to be right padded, while ids arriving full length from the SDK are
// already 64 hex characters and pass through unchanged.

/** The fixture window a chain market id corresponds to, when there is one. */
function windowFor(marketId: string): EventWindow | undefined {
  const target = marketId.toLowerCase();
  return eventWindows.find((w) => toBytes32(w.marketId).toLowerCase() === target);
}

function assetForMarket(marketId: string): Asset {
  return windowFor(marketId)?.asset ?? "BTC";
}

/**
 * The entry price is not in the RollSettled payload. Two ways to recover it,
 * in order of confidence:
 *   1. a winning roll pays 1 per contract, so stake divided by payout is the
 *      price actually paid
 *   2. otherwise fall back to the book price on the matching window
 * A losing roll on an unknown market leaves 0, which the console renders as 0c
 * rather than inventing a number.
 */
function entryCentsFrom(
  marketId: string,
  direction: Direction,
  stake: number,
  payout: number,
  won: boolean
): number {
  if (won && payout > 0 && stake > 0) {
    return Math.round((stake / payout) * 100);
  }
  const window = windowFor(marketId);
  if (!window) return 0;
  return direction === "UP" ? window.upAskCents : window.downAskCents;
}

function round2(n: number) {
  return Math.round(n * 100) / 100;
}
